package report

import (
	"bytes"
	_ "embed"
	"fmt"
	"html"
	"html/template"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
)

// Night navigation. Each report carries two marked nav blocks (above the
// title and after the footnote). A report is rendered before its successor
// exists, so the blocks are regenerated by Relink whenever a night is added
// and the changed files are republished. Links are relative — index.html
// and YYYY-MM-DD.html sit side by side on the server and on disk.

const navEnd = "<!--/nav-->"

func navStart(pos string) string { return "<!--nav:" + pos + "-->" }

var nightFile = regexp.MustCompile(`^(\d{4}-\d{2}-\d{2})\.html$`)

// navBlock renders one marked nav row. prev and next are nights ("" = none).
func navBlock(pos, night, prev, next string) string {
	var b strings.Builder
	b.WriteString(navStart(pos))
	fmt.Fprintf(&b, `<nav class="nights %s"><a href="index.html">All nights</a><span class="pn">`, pos)
	if prev != "" {
		fmt.Fprintf(&b, `<a rel="prev" href="%s.html">&larr; %s</a>`, prev, html.EscapeString(navLabel(prev, night)))
	} else {
		b.WriteString(`<span class="off">&larr; Earliest night</span>`)
	}
	if next != "" {
		fmt.Fprintf(&b, `<a rel="next" href="%s.html">%s &rarr;</a>`, next, html.EscapeString(navLabel(next, night)))
	} else {
		b.WriteString(`<span class="off">Latest night &rarr;</span>`)
	}
	b.WriteString(`</span></nav>`)
	b.WriteString(navEnd)
	return b.String()
}

// navLabel is the short form used in prev/next links: "31 Aug", with the
// year only when it differs from the night being viewed.
func navLabel(night, from string) string {
	t, err := time.Parse("2006-01-02", night)
	if err != nil {
		return night
	}
	if len(from) >= 4 && from[:4] != night[:4] {
		return t.Format("2 Jan 2006")
	}
	return t.Format("2 Jan")
}

// Nights lists the nights with a report in dir, oldest first.
func Nights(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var nights []string
	for _, e := range entries {
		if m := nightFile.FindStringSubmatch(e.Name()); m != nil && !e.IsDir() {
			nights = append(nights, m[1])
		}
	}
	sort.Strings(nights)
	return nights, nil
}

// Relink rewrites the nav blocks of every report in dir so prev/next point
// at the neighbouring nights that exist now. It returns the paths it
// changed, so the caller can republish just those. Reports without nav
// markers (rendered before navigation existed) are left alone.
func Relink(dir string) ([]string, error) {
	nights, err := Nights(dir)
	if err != nil {
		return nil, err
	}
	var changed []string
	for i, n := range nights {
		var prev, next string
		if i > 0 {
			prev = nights[i-1]
		}
		if i < len(nights)-1 {
			next = nights[i+1]
		}
		path := filepath.Join(dir, n+".html")
		page, err := os.ReadFile(path)
		if err != nil {
			return changed, err
		}
		out := page
		for _, pos := range []string{"top", "bottom"} {
			out = replaceBlock(out, pos, navBlock(pos, n, prev, next))
		}
		if bytes.Equal(out, page) {
			continue
		}
		if err := os.WriteFile(path, out, 0o644); err != nil {
			return changed, err
		}
		changed = append(changed, path)
	}
	return changed, nil
}

func replaceBlock(page []byte, pos, block string) []byte {
	start := bytes.Index(page, []byte(navStart(pos)))
	if start < 0 {
		return page
	}
	end := bytes.Index(page[start:], []byte(navEnd))
	if end < 0 {
		return page
	}
	end += start + len(navEnd)
	out := make([]byte, 0, len(page)-(end-start)+len(block))
	out = append(out, page[:start]...)
	out = append(out, block...)
	return append(out, page[end:]...)
}

// ── index page ───────────────────────────────────────────────────────────

//go:embed index.tmpl
var indexTmplSrc string

var indexTmpl = template.Must(template.New("index").Parse(indexTmplSrc))

type indexNight struct {
	File    string
	Label   string // "Wed 2–3 Sep"
	Summary string // opening of the verdict
	Pills   []string
}

type indexMonth struct {
	Label  string // "September 2026"
	Nights []indexNight
}

type indexData struct {
	Months []indexMonth
	Count  int
	CSS    template.CSS
}

var (
	verdictRe = regexp.MustCompile(`(?s)<p class="sub">(.*?)</p>`)
	tagRe     = regexp.MustCompile(`<[^>]+>`)
	indexRe   = regexp.MustCompile(`index (?:held at )?(\d+)`)
	onsetRe   = regexp.MustCompile(`Cloud arrived at (\d\d:\d\d)`)
)

// WriteIndex regenerates dir/index.html from the reports present and returns
// its path. The per-night summary is lifted from each report's verdict, so
// the index needs nothing but the files.
func WriteIndex(dir string) (string, error) {
	nights, err := Nights(dir)
	if err != nil {
		return "", err
	}
	var data indexData
	for i := len(nights) - 1; i >= 0; i-- { // newest first
		n := nights[i]
		t, err := time.Parse("2006-01-02", n)
		if err != nil {
			continue
		}
		month := t.Format("January 2006")
		if len(data.Months) == 0 || data.Months[len(data.Months)-1].Label != month {
			data.Months = append(data.Months, indexMonth{Label: month})
		}
		m := &data.Months[len(data.Months)-1]
		page, _ := os.ReadFile(filepath.Join(dir, n+".html"))
		summary, pills := summarise(page)
		m.Nights = append(m.Nights, indexNight{
			File: n + ".html", Label: nightShort(t), Summary: summary, Pills: pills,
		})
		data.Count++
	}
	data.CSS = template.CSS(reportCSS)

	path := filepath.Join(dir, "index.html")
	var buf bytes.Buffer
	if err := indexTmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return path, os.WriteFile(path, buf.Bytes(), 0o644)
}

// summarise pulls the verdict's opening and a couple of headline figures
// out of a rendered report. Anything it can't find is simply omitted.
func summarise(page []byte) (string, []string) {
	m := verdictRe.FindSubmatch(page)
	if m == nil {
		return "", nil
	}
	text := html.UnescapeString(strings.TrimSpace(tagRe.ReplaceAllString(string(m[1]), "")))
	text = strings.Join(strings.Fields(text), " ")
	var pills []string
	if im := indexRe.FindStringSubmatch(text); im != nil {
		pills = append(pills, "Index "+im[1])
	}
	if om := onsetRe.FindStringSubmatch(text); om != nil {
		pills = append(pills, "Cloud "+om[1])
	} else if strings.HasPrefix(text, "No cloud onset") {
		pills = append(pills, "Clear all night")
	}
	return truncate(text, 180), pills
}

// truncate cuts at a word boundary near max runes and marks the cut.
func truncate(s string, max int) string {
	r := []rune(s)
	if len(r) <= max {
		return s
	}
	cut := max
	for cut > max/2 && r[cut] != ' ' {
		cut--
	}
	return strings.TrimRight(string(r[:cut]), " ,;—") + "…"
}

// nightShort labels a night inside its month group: "Wed 2–3 Sep", or
// "Wed 30 Sep – 1 Oct" when the night straddles a month.
func nightShort(t time.Time) string {
	next := t.AddDate(0, 0, 1)
	if t.Month() == next.Month() {
		return fmt.Sprintf("%s %d–%d %s", t.Format("Mon"), t.Day(), next.Day(), t.Format("Jan"))
	}
	return fmt.Sprintf("%s %s – %s", t.Format("Mon"), t.Format("2 Jan"), next.Format("2 Jan"))
}
