// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Baseline struct {
	Target      string  `json:"target"`
	Filter      string  `json:"filter"`
	MedianStars float64 `json:"median_stars"`
	NFrames     int64   `json:"n_frames"`
	NNights     int64   `json:"n_nights"`
	UpdatedAt   string  `json:"updated_at"`
}

type Event struct {
	ID      int64  `json:"id"`
	NightID int64  `json:"night_id"`
	At      string `json:"at"`
	Kind    string `json:"kind"`
	Detail  string `json:"detail"`
	Cause   string `json:"cause"`
}

type Frame struct {
	ID            int64           `json:"id"`
	NightID       int64           `json:"night_id"`
	At            string          `json:"at"`
	Class         string          `json:"class"`
	ExposureSec   float64         `json:"exposure_sec"`
	Filter        string          `json:"filter"`
	Target        string          `json:"target"`
	DetectedStars int64           `json:"detected_stars"`
	Hfr           float64         `json:"hfr"`
	IndexPct      sql.NullFloat64 `json:"index_pct"`
}

type Night struct {
	ID           int64          `json:"id"`
	NightOf      string         `json:"night_of"`
	LogPath      string         `json:"log_path"`
	LogSha256    string         `json:"log_sha256"`
	CloudOnsetAt sql.NullString `json:"cloud_onset_at"`
	BaselineMode string         `json:"baseline_mode"`
	IngestedAt   string         `json:"ingested_at"`
}

type SkySample struct {
	ID         int64           `json:"id"`
	NightID    int64           `json:"night_id"`
	At         string          `json:"at"`
	Luminance  float64         `json:"luminance"`
	Volatility sql.NullFloat64 `json:"volatility"`
	ImagePath  string          `json:"image_path"`
}
