// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createNight = `-- name: CreateNight :exec
INSERT INTO nights (night_of, log_path, log_sha256, cloud_onset_at, baseline_mode, ingested_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateNightParams struct {
	NightOf      string         `json:"night_of"`
	LogPath      string         `json:"log_path"`
	LogSha256    string         `json:"log_sha256"`
	CloudOnsetAt sql.NullString `json:"cloud_onset_at"`
	BaselineMode string         `json:"baseline_mode"`
	IngestedAt   string         `json:"ingested_at"`
}

func (q *Queries) CreateNight(ctx context.Context, arg CreateNightParams) error {
	_, err := q.db.ExecContext(ctx, createNight,
		arg.NightOf,
		arg.LogPath,
		arg.LogSha256,
		arg.CloudOnsetAt,
		arg.BaselineMode,
		arg.IngestedAt,
	)
	return err
}

const deleteNight = `-- name: DeleteNight :exec
DELETE FROM nights WHERE night_of = ?
`

func (q *Queries) DeleteNight(ctx context.Context, nightOf string) error {
	_, err := q.db.ExecContext(ctx, deleteNight, nightOf)
	return err
}

const getNight = `-- name: GetNight :one
SELECT id, night_of, log_path, log_sha256, cloud_onset_at, baseline_mode, ingested_at
FROM nights WHERE night_of = ?
`

func (q *Queries) GetNight(ctx context.Context, nightOf string) (Night, error) {
	row := q.db.QueryRowContext(ctx, getNight, nightOf)
	var i Night
	err := row.Scan(
		&i.ID,
		&i.NightOf,
		&i.LogPath,
		&i.LogSha256,
		&i.CloudOnsetAt,
		&i.BaselineMode,
		&i.IngestedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (night_id, at, kind, detail, cause)
VALUES (?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	NightID int64  `json:"night_id"`
	At      string `json:"at"`
	Kind    string `json:"kind"`
	Detail  string `json:"detail"`
	Cause   string `json:"cause"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.NightID,
		arg.At,
		arg.Kind,
		arg.Detail,
		arg.Cause,
	)
	return err
}

const insertFrame = `-- name: InsertFrame :exec
INSERT INTO frames (night_id, at, class, exposure_sec, filter, target, detected_stars, hfr, index_pct)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertFrameParams struct {
	NightID       int64           `json:"night_id"`
	At            string          `json:"at"`
	Class         string          `json:"class"`
	ExposureSec   float64         `json:"exposure_sec"`
	Filter        string          `json:"filter"`
	Target        string          `json:"target"`
	DetectedStars int64           `json:"detected_stars"`
	Hfr           float64         `json:"hfr"`
	IndexPct      sql.NullFloat64 `json:"index_pct"`
}

func (q *Queries) InsertFrame(ctx context.Context, arg InsertFrameParams) error {
	_, err := q.db.ExecContext(ctx, insertFrame,
		arg.NightID,
		arg.At,
		arg.Class,
		arg.ExposureSec,
		arg.Filter,
		arg.Target,
		arg.DetectedStars,
		arg.Hfr,
		arg.IndexPct,
	)
	return err
}

const insertSkySample = `-- name: InsertSkySample :exec
INSERT INTO sky_samples (night_id, at, luminance, volatility, image_path)
VALUES (?, ?, ?, ?, ?)
`

type InsertSkySampleParams struct {
	NightID    int64           `json:"night_id"`
	At         string          `json:"at"`
	Luminance  float64         `json:"luminance"`
	Volatility sql.NullFloat64 `json:"volatility"`
	ImagePath  string          `json:"image_path"`
}

func (q *Queries) InsertSkySample(ctx context.Context, arg InsertSkySampleParams) error {
	_, err := q.db.ExecContext(ctx, insertSkySample,
		arg.NightID,
		arg.At,
		arg.Luminance,
		arg.Volatility,
		arg.ImagePath,
	)
	return err
}

const listBaselines = `-- name: ListBaselines :many
SELECT target, filter, median_stars, n_frames, n_nights, updated_at
FROM baselines ORDER BY target, filter
`

func (q *Queries) ListBaselines(ctx context.Context) ([]Baseline, error) {
	rows, err := q.db.QueryContext(ctx, listBaselines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Baseline
	for rows.Next() {
		var i Baseline
		if err := rows.Scan(
			&i.Target,
			&i.Filter,
			&i.MedianStars,
			&i.NFrames,
			&i.NNights,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClearLightFrames = `-- name: ListClearLightFrames :many
SELECT f.detected_stars, n.night_of
FROM frames f
JOIN nights n ON n.id = f.night_id
WHERE f.class = 'light'
  AND f.target = ?
  AND f.filter = ?
  AND (n.cloud_onset_at IS NULL OR f.at < n.cloud_onset_at)
ORDER BY n.night_of, f.at
`

type ListClearLightFramesParams struct {
	Target string `json:"target"`
	Filter string `json:"filter"`
}

type ListClearLightFramesRow struct {
	DetectedStars int64  `json:"detected_stars"`
	NightOf       string `json:"night_of"`
}

// Clear-sky light frames for one (target, filter) across all nights: frames
// before that night's cloud onset, or the whole night when no onset. Feeds
// the rolling historical baseline.
func (q *Queries) ListClearLightFrames(ctx context.Context, arg ListClearLightFramesParams) ([]ListClearLightFramesRow, error) {
	rows, err := q.db.QueryContext(ctx, listClearLightFrames, arg.Target, arg.Filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClearLightFramesRow
	for rows.Next() {
		var i ListClearLightFramesRow
		if err := rows.Scan(&i.DetectedStars, &i.NightOf); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, night_id, at, kind, detail, cause
FROM events WHERE night_id = ? ORDER BY at
`

func (q *Queries) ListEvents(ctx context.Context, nightID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, nightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.NightID,
			&i.At,
			&i.Kind,
			&i.Detail,
			&i.Cause,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrames = `-- name: ListFrames :many
SELECT id, night_id, at, class, exposure_sec, filter, target, detected_stars, hfr, index_pct
FROM frames WHERE night_id = ? ORDER BY at
`

func (q *Queries) ListFrames(ctx context.Context, nightID int64) ([]Frame, error) {
	rows, err := q.db.QueryContext(ctx, listFrames, nightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Frame
	for rows.Next() {
		var i Frame
		if err := rows.Scan(
			&i.ID,
			&i.NightID,
			&i.At,
			&i.Class,
			&i.ExposureSec,
			&i.Filter,
			&i.Target,
			&i.DetectedStars,
			&i.Hfr,
			&i.IndexPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNights = `-- name: ListNights :many
SELECT id, night_of, log_path, log_sha256, cloud_onset_at, baseline_mode, ingested_at
FROM nights ORDER BY night_of DESC
`

func (q *Queries) ListNights(ctx context.Context) ([]Night, error) {
	rows, err := q.db.QueryContext(ctx, listNights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Night
	for rows.Next() {
		var i Night
		if err := rows.Scan(
			&i.ID,
			&i.NightOf,
			&i.LogPath,
			&i.LogSha256,
			&i.CloudOnsetAt,
			&i.BaselineMode,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkySamples = `-- name: ListSkySamples :many
SELECT id, night_id, at, luminance, volatility, image_path
FROM sky_samples WHERE night_id = ? ORDER BY at
`

func (q *Queries) ListSkySamples(ctx context.Context, nightID int64) ([]SkySample, error) {
	rows, err := q.db.QueryContext(ctx, listSkySamples, nightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkySample
	for rows.Next() {
		var i SkySample
		if err := rows.Scan(
			&i.ID,
			&i.NightID,
			&i.At,
			&i.Luminance,
			&i.Volatility,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBaseline = `-- name: UpsertBaseline :exec
INSERT INTO baselines (target, filter, median_stars, n_frames, n_nights, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (target, filter) DO UPDATE SET
    median_stars = excluded.median_stars,
    n_frames     = excluded.n_frames,
    n_nights     = excluded.n_nights,
    updated_at   = excluded.updated_at
`

type UpsertBaselineParams struct {
	Target      string  `json:"target"`
	Filter      string  `json:"filter"`
	MedianStars float64 `json:"median_stars"`
	NFrames     int64   `json:"n_frames"`
	NNights     int64   `json:"n_nights"`
	UpdatedAt   string  `json:"updated_at"`
}

func (q *Queries) UpsertBaseline(ctx context.Context, arg UpsertBaselineParams) error {
	_, err := q.db.ExecContext(ctx, upsertBaseline,
		arg.Target,
		arg.Filter,
		arg.MedianStars,
		arg.NFrames,
		arg.NNights,
		arg.UpdatedAt,
	)
	return err
}
